spring.h2.console.enabled: true
spring.datasource.url: jdbc:h2:mem:carddb
spring.security.enabled: true


application:
  users:
    - username: user
      password: password
      roles: VIEWER
    - username: admin
      password: password
      roles: VIEWER,ADMIN